### PR TITLE
[init] Basic changes to work with netjsonconfig

### PR DESCRIPTION
**Pull request by atb00ker**
Made these changes for working with https://github.com/openwisp/django-netjsonconfig/pull/96.

### CODE REVIEW

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
is it ready to merge?

**Comment by atb00ker** [comment]
Yes, I think it's ready! :smile: 
Shall I merge it or wait for @nemesisdesign's review?

Thanks.

**Comment by auvipy** [comment]
Could you share a few screenshots?

**Comment by auvipy** [comment]
Looks good overall to me. let's move forward, we can handle future issues separately if anything arises.

**Pull request merged**
